# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: onebranch.pipeline.signing@1
  inputs:
    command: 'sign'
    signing_environment: 'azure-ado'
    signing_profile: 'external_distribution'
    search_root: '$(Build.SourcesDirectory)'
